### ISSUE TITLE
./main.native: symbol lookup error: ./main.native: undefined symbol: Z3_fixedpoint_pop

### ISSUE THREAD

**Issue by citceae** [wslee/duet#1]
After “# Compilation successful.”， I found that main.native created in main folder is 0kb; _build/src/main.native seems normal but whichever main.native i used,  I got the above error message "./main.native: symbol lookup error: ./main.native: undefined symbol: Z3_fixedpoint_pop".  There is another version of z3 on my pc(4.12.2), but opam has specified 4.8.1 z3, does anyone know how to solve this problem?

**Comment by wslee** [comment]
Perhaps because you didn't set the LD LIBRARY PATH properly. Make sure 4.8.1 z3 is preferred by typing the following command.  

$ export LD_LIBRARY_PATH=[OPAM home directory (e.g., ~/.opam)]/[your OCaml version (e.g., 4.08.0)]/lib/z3:$LD_LIBRARY_PATH
